#define             PROGRAM      	1
#define             FUNCTION     	2
#define             CONST        	3
#define             VAR          	4
#define             INTEGER     	5
#define             BEGINN       	6
#define             END       	 	7
#define             IF           	8
#define             THEN         	9
#define             ELSE         	10
#define             DO         	 	11
#define		    FOR	    	 	12
#define		    TO	     	 	13
#define             WRITE	 	14
#define             READ 	 	15
#define             ID           	16
#define             INTLITERAL	 	17
#define             SEMICOLON	 	18
#define             DOSPUNTOS	 	19
#define             PUNTO	 	20
#define             COMA	 	21
#define             LPAREN	 	22
#define             RPAREN	 	23
#define		    ASIGNOP	 	24
#define		    PLUSOP	 	25
#define		    MINUSOP	 	26
#define		    DIV	    	 	27
#define		    MULT	 	28
#define		    ENTERO	 	29
#define		    WHILE	 	30
#define 	    ERR			31
#define		    STRING		32
